#cloud-config
package_update: true
package_upgrade: true

manage_resolv_conf: true
resolv_conf:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

packages:
  - qemu-guest-agent
  - docker.io
  - docker-compose-plugin
  - ca-certificates
  - curl
  - bash

runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl enable --now docker
